### ISSUE TITLE
Use Qtconcurrent::run instead of timer event 

### ISSUE THREAD

**Issue by Param-Uttarwar** [Myzhar/QtOpenCVViewerGl#1]
Multiple instances of startTimer(0), slows down the GUI for some reasons. If you trigger the command for 4-5 times, GUI gets really slow. Can use threads for the same operation

**Comment by Myzhar** [comment]
You are right... normally I use it in threads. This is a simple demo and
using thread can only make the things more complicated 😉

## 

Walter Lucetti

email: myzhar@gmail.com
web: www.robot-home.it - www.opencv.it
project:  http://myzharbot.robot-home.it
Il 03/Lug/2015 08:04, "Param-Uttarwar" notifications@github.com ha
scritto:

**Comment by Param-Uttarwar** [comment]
K....thanks anyways, your code was of great help
