### ISSUE TITLE
Error while manual resizing

### ISSUE THREAD

**Issue by ouzan19** [Myzhar/QtOpenCVViewerGl#6]
When using the widget stand-alone, if the widget window is resized by the user manually, the program crashes.

**Comment by ouzan19** [comment]
While glDrawPixels() is updating the screen, if the window size is changed, it crashes. To avoid this, a mutex is needed. This mutex should be locked before glDrawPixels() and unlock after. Also, the mutex should be locked at the very beginning of showImage() and unlocked at the end of showImage(). Thus, while openGL drawing pixels into the window, the window cannot change and vice-versa.

**Comment by Myzhar** [comment]
@ouzan19 can you please submit a pull request with the patch to solve this issue? 
Thank you
Walter

**Comment by ouzan19** [comment]
solved by PR # #8
